### ISSUE TITLE
Issue with caching column names in SQLite

### ISSUE THREAD

**Issue by tony-o** [CurtTilmes/perl6-db#1]
Issue can be reproduced with this minimal script

```perl6
use DB::SQLite;
use Data::Dump;

END {
  try 'xyz.sqlite3'.IO.unlink;
};

(my DB::SQLite $db .=new(:filename<xyz.sqlite3>)).connect;

$db.execute('create table test (id integer primary key autoincrement, dt varchar(32) )');
my $sth = $db.db.prepare('insert into test (dt) values (?)');
$sth.execute('hello world');
$sth.execute( ('a'..'z').roll(10).join ) for 0..18;
$sth.finish;
say $db.query('select id from test where dt = ?', 'hello world').hash;
# line 15 ^ caches .names to be <id>
say $db.query('select * from test where id = ?', 1).hash;
# line 17 ^ this uses the cached $keys from line 15
```

I would expect the final `.say` to result in a hash similar to `{ dt => 'hello world', id => 1 }` where it instead is `{ id => 1 }`.  This only happens if the method in `DB::Result::&keys` caches the `$.names` call.  I have a PR that I'm sending for this issue.  Perhaps this isn't an issue with the other `DB::*` modules in which case maybe caching is better and then setting a flag in whatever module to determine whether that call is cacheable but this is what I came up with on the plane :)

**Comment by CurtTilmes** [comment]
BTW, Don't call `.connect`:

    (my DB::SQLite $db .=new(:filename<xyz.sqlite3>)).connect;

should be just

    my DB::SQLite $db .=new(:filename<xyz.sqlite3>);

it will call `.connect` when it needs to.

**Comment by CurtTilmes** [comment]
Let me know if the commit above is sufficient and I'll do a release.  (Feel free to update your PR and I'll do that too).

**Comment by tony-o** [comment]
@CurtTilmes - that fixes it.  I also had a README update showing modules using `DB`, I can do that as a separate PR if you're interested -
